<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/project.proto

namespace Projection;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>projection.ProjectionResponse</code>
 */
class ProjectionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     */
    protected $eventId = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Any operation = 2;</code>
     */
    protected $operation = null;
    /**
     * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $eventId
     *     @type \Google\Protobuf\Any $operation
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Project::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     * @return string
     */
    public function getEventId()
    {
        return $this->eventId;
    }

    /**
     * Generated from protobuf field <code>string eventId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any operation = 2;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getOperation()
    {
        return $this->operation;
    }

    public function hasOperation()
    {
        return isset($this->operation);
    }

    public function clearOperation()
    {
        unset($this->operation);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any operation = 2;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->operation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

}

