<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/project.proto

namespace Projection;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>projection.ProjectionRequest</code>
 */
class ProjectionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string eventType = 1;</code>
     */
    protected $eventType = '';
    /**
     * Generated from protobuf field <code>string eventId = 2;</code>
     */
    protected $eventId = '';
    /**
     * Generated from protobuf field <code>string stream = 3;</code>
     */
    protected $stream = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct eventPayload = 4;</code>
     */
    protected $eventPayload = null;
    /**
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $eventType
     *     @type string $eventId
     *     @type string $stream
     *     @type \Google\Protobuf\Struct $eventPayload
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Project::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string eventType = 1;</code>
     * @return string
     */
    public function getEventType()
    {
        return $this->eventType;
    }

    /**
     * Generated from protobuf field <code>string eventType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventType($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string eventId = 2;</code>
     * @return string
     */
    public function getEventId()
    {
        return $this->eventId;
    }

    /**
     * Generated from protobuf field <code>string eventId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->eventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stream = 3;</code>
     * @return string
     */
    public function getStream()
    {
        return $this->stream;
    }

    /**
     * Generated from protobuf field <code>string stream = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStream($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct eventPayload = 4;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getEventPayload()
    {
        return $this->eventPayload;
    }

    public function hasEventPayload()
    {
        return isset($this->eventPayload);
    }

    public function clearEventPayload()
    {
        unset($this->eventPayload);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct eventPayload = 4;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setEventPayload($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->eventPayload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

}

