<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/project.proto

namespace Projection;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>projection.UpdateOne</code>
 */
class UpdateOne extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct filter = 1;</code>
     */
    protected $filter = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct update = 2;</code>
     */
    protected $update = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $filter
     *     @type \Google\Protobuf\Struct $update
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Project::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct filter = 1;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getFilter()
    {
        return $this->filter;
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct filter = 1;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->filter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct update = 2;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getUpdate()
    {
        return $this->update;
    }

    public function hasUpdate()
    {
        return isset($this->update);
    }

    public function clearUpdate()
    {
        unset($this->update);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct update = 2;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setUpdate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->update = $var;

        return $this;
    }

}

